spring:
   profiles:
      active:
      - dev
---
spring:
  profiles: dev
  application:
      name: microconfig-test-dev-aa
---
spring:
 profiles: default
 application:
      name: microconfig-test-default
